name: Env variable
on:
  workflow_dispatch

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: echo "$JOB_NAME"
      env:
        JOB_NAME: ${{ vars.JOB_NAME }}
       
